# Generated by Django 5.2.11 on 2026-02-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "license_year",
                    models.IntegerField(help_text="Year the license was issued"),
                ),
                (
                    "resident_status",
                    models.CharField(
                        choices=[
                            ("resident", "Resident"),
                            ("non_resident", "Non-Resident"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor"),
                            ("fair", "Fair"),
                            ("good", "Good"),
                            ("very_good", "Very Good"),
                            ("excellent", "Excellent"),
                            ("mint", "Mint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible on public profile"
                    ),
                ),
                (
                    "trade_eligible",
                    models.BooleanField(
                        default=False, help_text="Available for trade offers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_items",
                        to="core.county",
                    ),
                ),
                (
                    "license_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_items",
                        to="core.licensetype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item",
                "verbose_name_plural": "Collection Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="collections/")),
                ("sort_order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="collections.collectionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item Image",
                "verbose_name_plural": "Collection Item Images",
                "ordering": ["sort_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WantedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_min", models.IntegerField(blank=True, null=True)),
                ("year_max", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wanted_items",
                        to="core.county",
                    ),
                ),
                (
                    "license_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wanted_items",
                        to="core.licensetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wanted Item",
                "verbose_name_plural": "Wanted Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["owner", "-created_at"], name="collections_owner_i_f9323b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(
                fields=["is_public", "trade_eligible"],
                name="collections_is_publ_06fcaf_idx",
            ),
        ),
    ]
