# Generated by Django 5.0 on 2026-02-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible on public profile'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='license_year',
            field=models.IntegerField(blank=True, help_text='Year the license was issued', null=True),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='trade_eligible',
            field=models.BooleanField(default=True, help_text='Available for trade offers'),
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='notes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
