# Generated by Django 5.0 on 2026-03-25 04:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_collection_state(apps, schema_editor):
    CollectionItem = apps.get_model('collections', 'CollectionItem')
    WantedItem = apps.get_model('collections', 'WantedItem')
    State = apps.get_model('core', 'State')

    pa_state = State.objects.filter(code='PA').first()

    for item in CollectionItem.objects.all().iterator():
        if item.state_id:
            continue
        county = getattr(item, 'county', None)
        if county and county.state_id:
            item.state_id = county.state_id
        elif pa_state:
            item.state_id = pa_state.id
        if item.state_id:
            item.save(update_fields=['state'])

    for item in WantedItem.objects.all().iterator():
        if item.state_id:
            continue
        county = getattr(item, 'county', None)
        if county and county.state_id:
            item.state_id = county.state_id
        elif pa_state:
            item.state_id = pa_state.id
        if item.state_id:
            item.save(update_fields=['state'])


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_collectionitem_license_types_m2m'),
        ('core', '0005_referencedatasuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='shape',
            field=models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('square', 'Square'), ('button_disc', 'Button/Disc'), ('tag_with_hole', 'Tag (with hole)'), ('strip', 'Strip'), ('irregular_custom', 'Irregular/Custom'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Issuing state for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='core.state'),
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_items', to='core.state'),
        ),
        migrations.RunPython(backfill_collection_state, reverse_code=migrations.RunPython.noop),
    ]
