# Generated by Django 5.0 on 2026-07-10 06:07

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_collectionitem_era_label_and_more'),
        ('core', '0006_itemcategory_licensetype_first_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='addons_attached',
            field=models.BooleanField(blank=True, help_text='For licenses with add-ons: True = tags/stamps still physically attached; False = detached/used; null = unknown', null=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='category',
            field=models.ForeignKey(default=apps.core.models.get_default_item_category, on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='core.itemcategory'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='item_kind',
            field=models.CharField(choices=[('license', 'License'), ('addon', 'Add-on / Stamp / Tag')], default='license', help_text='Base license vs. standalone stamp/tag/permit', max_length=20),
        ),
    ]
