# Generated by Django 5.0 on 2026-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0008_backfill_item_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='condition_grade',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent'), ('near_mint', 'Near Mint'), ('mint', 'Mint')], max_length=20),
        ),
    ]
