# Generated by Django 5.0 on 2026-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0009_form_overhaul_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='acquired_note',
            field=models.CharField(blank=True, help_text='Private. When and where — "Mar 2026, Bloomsburg".', max_length=120),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='private_note',
            field=models.TextField(blank=True, help_text='Private. A note to yourself about this piece.', max_length=1000),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Private. What you paid, for your own records and an insurance export. Never shown to anybody else.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionitemimage',
            name='image_role',
            field=models.CharField(choices=[('front', 'Featured · front'), ('back', 'Back'), ('detail', 'Detail')], default='detail', help_text='What this photograph is of.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='collectionitemimage',
            constraint=models.UniqueConstraint(condition=models.Q(('image_role__in', ('front', 'back'))), fields=('collection_item', 'image_role'), name='one_item_photograph_per_named_slot'),
        ),
    ]
