# Generated by Django 5.0 on 2026-08-05 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0010_collectionitem_acquired_note_and_more'),
        ('core', '0011_termsversion_termsacceptance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collectionitem',
            name='collections_is_publ_06fcaf_idx',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='trade_wants',
            field=models.CharField(blank=True, help_text='What you would take for it. Shown beside the piece.', max_length=250),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='tradeability',
            field=models.CharField(choices=[('unset', 'Not answered'), ('open', 'Open to trade offers'), ('closed', 'Not for trade')], default='unset', help_text='Your own answer. Whether the piece can take an offer right now also depends on whether it is on a live lot, and that is worked out rather than stored.', max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='trade_eligible',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['is_public', 'tradeability'], name='collections_is_publ_1f4d3c_idx'),
        ),
    ]
