# Generated by Django 5.0 on 2026-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0013_tradeable_unless_you_say_otherwise'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='disposition',
            field=models.CharField(choices=[('held', 'In my hands'), ('traded', 'Traded away here'), ('sold_elsewhere', 'Sold elsewhere'), ('given_away', 'Given away'), ('lost', 'Lost')], default='held', help_text='Whether the piece is still physically yours. Anything but "held" takes it off the trade board and out of offers.', max_length=20),
        ),
    ]
