# Generated by Django 5.0 on 2026-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0014_collectionitem_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='condition_description',
            field=models.TextField(blank=True, help_text='The flaws said plainly — foxing, the pin, tears, tape.', max_length=2000),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='is_restored',
            field=models.BooleanField(default=False),
        ),
    ]
