# Generated by Django 5.0 on 2026-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0015_collectionitem_condition_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='condition_grade',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very good'), ('excellent', 'Excellent'), ('near_mint', 'Near mint'), ('mint', 'Mint')], max_length=20),
        ),
    ]
