# Generated by Django 5.0 on 2026-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0016_alter_collectionitem_condition_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='disposition',
            field=models.CharField(choices=[('held', 'In my hands'), ('sold', 'Sold here'), ('traded', 'Traded away here'), ('sold_elsewhere', 'Sold elsewhere'), ('given_away', 'Given away'), ('lost', 'Lost')], default='held', help_text='Whether the piece is still physically yours. Anything but "held" takes it off the trade board and out of offers.', max_length=20),
        ),
    ]
