# Generated by Django 5.2.11 on 2026-02-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collections", "0001_initial"),
        ("listings", "0002_listing_allow_cash_listing_buy_now_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="collections.collectionitem",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="favorites_f_user_id_3c3f17_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(
                                ("collection_item__isnull", True),
                                ("listing__isnull", False),
                            ),
                            models.Q(
                                ("collection_item__isnull", False),
                                ("listing__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="favorite_xor_listing_collection",
                    )
                ],
            },
        ),
    ]
