# Generated by Django 5.0 on 2026-02-16 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_alter_collectionitem_is_public_and_more'),
        ('favorites', '0001_initial'),
        ('listings', '0004_listing_resident_status_listingquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('user', 'listing'), name='favorite_unique_user_listing'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('collection_item__isnull', False)), fields=('user', 'collection_item'), name='favorite_unique_user_collection_item'),
        ),
    ]
