# Generated by Django 5.0 on 2026-08-03 21:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0018_listing_allow_offers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Offered item price, excluding platform fee and shipping.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_to', models.ForeignKey(blank=True, help_text='Set when this offer is a response to another. Sellers may only counter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counteroffers', to='offers.offer')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.listing')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', '-created_at'], name='offers_offe_listing_3ae1a7_idx'), models.Index(fields=['from_user', '-created_at'], name='offers_offe_from_us_52bbdd_idx'), models.Index(fields=['to_user', '-created_at'], name='offers_offe_to_user_3582fd_idx'), models.Index(fields=['status'], name='offers_offe_status_3245b3_idx')],
            },
        ),
    ]
