# Generated by Django 5.0 on 2026-07-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_payer',
            field=models.CharField(choices=[('buyer', 'Buyer pays shipping'), ('seller', 'Seller pays (free shipping)')], default='buyer', help_text='Snapshot of the listing shipping-payer choice at purchase', max_length=10),
        ),
    ]
