# Generated by Django 5.0 on 2026-08-03 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_allow_offers'),
        ('orders', '0003_shipping_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('buyer', models.F('seller')), _negated=True), name='order_buyer_is_not_seller'),
        ),
    ]
