# Generated by Django 5.0 on 2026-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_messaging_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='listing_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Saved defaults applied to new listings (shipping config, auto-relist, bid increment, ...)'),
        ),
    ]
