# Generated by Django 5.0 on 2026-08-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow_follow_unique_follow_follow_no_self_follow'),
        ('core', '0010_marketplacesettings_ship_by_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_county',
            field=models.ForeignKey(blank=True, help_text='Picked from the same unit list the listings use.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.geographicunit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.state'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='showcase_layout',
            field=models.CharField(choices=[('case', 'Display case first'), ('map', 'Map first'), ('one', 'One piece at a time'), ('collection', 'Just the collection')], default='case', help_text='The order visitors see your profile in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, editable=False, help_text='Superseded by home_county. Retained for anything migrated from free text that could not be matched to a unit.', max_length=50),
        ),
    ]
