# Generated by Django 5.0 on 2026-08-27 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_auction_extensions'),
        ('messaging', '0002_merge_pair_threads'),
        ('trades', '0007_carry_the_anchor_off_the_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_listing_conversation',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Most recent listing context — display only, never identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='trade_offer',
            field=models.ForeignKey(blank=True, help_text='Most recent trade context — display only, never identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='trades.tradeoffer'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='one_thread_per_pair'),
        ),
    ]
