# Generated by Django 5.0 on 2026-08-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_auction_extensions'),
        ('messaging', '0004_conversationmember_messagingsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_messages', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.CharField(choices=[('scam', 'Scam or fraud'), ('counterfeit', 'Fake or counterfeit item'), ('harassment', 'Harassment or threats'), ('hate', 'Hate speech'), ('underage', 'Someone may be underage'), ('spam', 'Spam'), ('other', 'Something else')], max_length=20),
        ),
    ]
