# Generated by Django 5.2.11 on 2026-02-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("state", models.CharField(default="PA", max_length=2)),
                ("fips_code", models.CharField(blank=True, max_length=5)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "County",
                "verbose_name_plural": "Counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LicenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "License Type",
                "verbose_name_plural": "License Types",
                "ordering": ["name"],
            },
        ),
    ]
