# Generated by Django 5.0 on 2026-02-16 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marketplacesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='trade_label_fee_amount',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Flat fee charged per trader when using in-app trade label purchase.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
