# Generated by Django 5.0 on 2026-03-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_reference_data(apps, schema_editor):
    GeographicUnit = apps.get_model('core', 'GeographicUnit')
    LicenseType = apps.get_model('core', 'LicenseType')

    GeographicUnit.objects.filter(name__iexact='Statewide').update(is_statewide=True)
    LicenseType.objects.filter(category='eligibility').update(category='holder_eligibility')
    LicenseType.objects.filter(category='addon').update(category='addon_type')
    LicenseType.objects.all().update(is_system_value=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state_geographicunit_licensetype_enrich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('new_value', 'New Value'), ('correction', 'Correction'), ('other', 'Other')], default='new_value', max_length=20)),
                ('target_model', models.CharField(choices=[('state', 'State'), ('geographic_unit', 'Geographic Unit'), ('license_type', 'License Type'), ('listing', 'Listing'), ('collection_item', 'Collection Item'), ('other', 'Other')], default='other', max_length=30)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('current_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField()),
                ('source_or_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='geographicunit',
            new_name='core_geogra_state_i_1b0ab3_idx',
            old_name='core_gu_state_name_idx',
        ),
        migrations.RenameIndex(
            model_name='geographicunit',
            new_name='core_geogra_state_i_fd62b8_idx',
            old_name='core_gu_state_utype_idx',
        ),
        migrations.RenameIndex(
            model_name='licensetype',
            new_name='core_licens_state_i_c7b509_idx',
            old_name='core_lt_state_cat_idx',
        ),
        migrations.AddField(
            model_name='geographicunit',
            name='geo_data_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='geographicunit',
            name='is_statewide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geographicunit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geographicunit',
            name='unit_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='is_system_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='agency_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='state',
            name='agency_name_historical',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='state',
            name='issuance_scope',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='state',
            name='licensing_start_source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='licensing_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='min_year_source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='category',
            field=models.CharField(choices=[('residency', 'Residency'), ('holder_eligibility', 'Holder Eligibility'), ('activity_scope', 'Activity Scope'), ('duration', 'Duration'), ('addon_type', 'Add-on Type'), ('material', 'Physical Form / Material'), ('shape', 'Shape'), ('colors', 'Color(s)')], default='residency', max_length=30),
        ),
        migrations.AddField(
            model_name='referencedatasuggestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reference_data_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencedatasuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_data_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(normalize_reference_data, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='referencedatasuggestion',
            index=models.Index(fields=['status', 'created_at'], name='core_refere_status_941a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='referencedatasuggestion',
            index=models.Index(fields=['target_model', 'target_id'], name='core_refere_target__c0f383_idx'),
        ),
    ]
