# Generated by Django 5.0 on 2026-07-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_referencedatasuggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Sporting Antiques', max_length=60)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='licensetype',
            name='first_year',
            field=models.IntegerField(blank=True, help_text='First year this product existed under this name/form', null=True),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='hunting_method',
            field=models.CharField(blank=True, help_text='Only methods visible on the artifact: Archery, Muzzleloader, Firearm', max_length=30),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='instrument',
            field=models.CharField(blank=True, choices=[('stamp', 'Stamp'), ('tag', 'Tag'), ('permit', 'Permit'), ('license', 'License'), ('fee', 'Fee'), ('certification', 'Certification')], help_text='What the artifact physically is (addon rows only)', max_length=20),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='last_year',
            field=models.IntegerField(blank=True, help_text='Last year issued (blank = still issued or unknown)', null=True),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='target_species',
            field=models.CharField(blank=True, help_text='e.g. Deer, Antlerless Deer, Turkey, Waterfowl (addon rows only)', max_length=50),
        ),
    ]
