# Generated by Django 5.0 on 2026-07-31 21:43

from django.db import migrations
from django.db.models import Min


def set_federal_min_year(apps, schema_editor):
    """Backfill the Federal pseudo-state's year floor from the earliest federal
    item already on record (the 1934 duck stamp). Data-driven, not hardcoded —
    fresh databases get the same value from the seed_license_types command after
    the rows are loaded. If no federal rows exist yet, leave it null for the
    seeder to set."""
    State = apps.get_model('core', 'State')
    LicenseType = apps.get_model('core', 'LicenseType')
    fd = State.objects.filter(code='FD', min_license_year__isnull=True).first()
    if not fd:
        return
    earliest = (
        LicenseType.objects.filter(state=fd, first_year__isnull=False)
        .aggregate(m=Min('first_year'))['m']
    )
    if earliest:
        fd.min_license_year = earliest
        fd.save(update_fields=['min_license_year'])


def unset_federal_min_year(apps, schema_editor):
    State = apps.get_model('core', 'State')
    State.objects.filter(code='FD').update(min_license_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_item_category'),
    ]

    operations = [
        migrations.RunPython(set_federal_min_year, unset_federal_min_year),
    ]
