# Generated by Django 5.0 on 2026-08-05 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_unit_label_is_a_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='ship_by_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Days a seller has to dispatch after payment clears. Quoted to buyers on the listing page and printed as a date on the order. No background job enforces it yet, so it is a promise rather than a constraint — do not shorten it without one.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
