# Generated by Django 5.0 on 2026-08-05 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_marketplacesettings_ship_by_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='As shown to members — "1.2".', max_length=20, unique=True)),
                ('summary', models.TextField(help_text='The short version, shown beside the acceptance checkbox.')),
                ('body', models.TextField(blank=True, help_text='The full text.')),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terms Version',
                'verbose_name_plural': 'Terms Versions',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(default='registration', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='core.termsversion')),
            ],
            options={
                'verbose_name': 'Terms Acceptance',
                'verbose_name_plural': 'Terms Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='termsacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'terms'), name='one_acceptance_per_version'),
        ),
    ]
