# Generated by Django 5.0 on 2026-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_termsversion_termsacceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='category',
            field=models.CharField(choices=[('residency', 'Residency'), ('holder_eligibility', 'Holder Eligibility'), ('activity_scope', 'Activity Scope'), ('duration', 'Duration'), ('addon_type', 'Add-on Type'), ('material', 'Physical Form / Material'), ('issue_class', 'Issue Class'), ('shape', 'Shape'), ('colors', 'Color(s)')], default='residency', max_length=30),
        ),
    ]
