# Generated by Django 5.0 on 2026-10-08 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_licensetype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacesettings',
            name='ship_by_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Business days a seller has to dispatch after payment clears. Quoted to buyers, printed as a date on the order, and enforced by the non-shipment strike (apps/orders/clock.py).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
