# Generated by Django 5.0 on 2026-08-27 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0003_remove_conversation_unique_listing_conversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_enabled', models.BooleanField(default=True, help_text='Master switch for the automated message scan.')),
                ('use_classifier', models.BooleanField(default=True, help_text='Tier 2: score every message with the free moderation API (needs OPENAI_API_KEY in the environment; skipped quietly without it).')),
                ('use_escalation', models.BooleanField(default=True, help_text='Tier 3: flagged threads are read in context by Claude, which judges intent (needs ANTHROPIC_API_KEY).')),
                ('escalation_model', models.CharField(default='claude-haiku-4-5-20251001', help_text='Model used for the intent read. Haiku keeps it at pennies.', max_length=60)),
                ('watched_categories', models.TextField(default='sexual/minors, harassment, harassment/threatening, hate, hate/threatening, violence, self-harm, self-harm/intent, illicit/violent', help_text='Classifier categories that count, comma-separated. Plain adult "sexual" is deliberately absent — consenting adults are not our business; add it here if that changes.')),
                ('urgent_categories', models.TextField(default='sexual/minors, harassment/threatening, hate/threatening, self-harm/intent, illicit/violent', help_text='Categories that page staff immediately instead of waiting in the queue. Anything minor-related belongs here.')),
                ('flag_threshold', models.FloatField(default=0.4, help_text='Classifier score at or above this flags a message for review.')),
                ('urgent_threshold', models.FloatField(default=0.8, help_text='Score at or above this, in an urgent category, pages staff.')),
                ('heated_window_hours', models.PositiveIntegerField(default=24, help_text='Window for the heated-thread check.')),
                ('heated_message_count', models.PositiveIntegerField(default=3, help_text='Flagged messages from BOTH sides within the window before a thread is surfaced as heated.')),
                ('escalation_context_messages', models.PositiveIntegerField(default=12, help_text='How many surrounding messages Claude reads when judging intent.')),
                ('scan_batch_size', models.PositiveIntegerField(default=50, help_text='Messages scanned per sweep of the cron command.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderation settings',
                'verbose_name_plural': 'Moderation settings',
            },
        ),
        migrations.CreateModel(
            name='WatchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Matched case-insensitively. With "is regex" off, matched as a whole phrase.', max_length=200)),
                ('is_regex', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('grooming', 'Minor safety / grooming'), ('threat', 'Threat'), ('slur', 'Slur'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('review', 'Review'), ('urgent', 'Urgent — page staff')], default='review', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Watch term',
                'verbose_name_plural': 'Watch terms',
                'ordering': ['category', 'term'],
            },
        ),
        migrations.CreateModel(
            name='MessageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('classifier_scores', models.JSONField(blank=True, null=True)),
                ('escalation_verdict', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message scan',
                'verbose_name_plural': 'Message scans',
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('term', 'Watch term'), ('classifier', 'Classifier'), ('escalation', 'Claude escalation'), ('heated', 'Heated thread')], max_length=20)),
                ('severity', models.CharField(choices=[('review', 'Review'), ('urgent', 'Urgent')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('summary', models.TextField(blank=True, help_text='Why it surfaced — the rule name, the category score, or Claude’s one-line rationale.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='messaging.message')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation event',
                'verbose_name_plural': 'Moderation events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity', '-created_at'], name='moderation__status_b6e680_idx')],
            },
        ),
    ]
