# Generated by Django 5.2.11 on 2026-02-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collections", "0001_initial"),
        ("listings", "0002_listing_allow_cash_listing_buy_now_price_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_shipment", "Pending Shipment"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_shipment",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("ship_by_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeFeeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_transactions",
                        to="trades.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_fee_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Fee Transaction",
                "verbose_name_plural": "Trade Fee Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("countered", "Countered"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash component of the trade offer",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offers",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Offer",
                "verbose_name_plural": "Trade Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeOfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("offered", "Offered"), ("requested", "Requested")],
                        max_length=20,
                    ),
                ),
                (
                    "collection_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offer_items",
                        to="collections.collectionitem",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trades.tradeoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Offer Item",
                "verbose_name_plural": "Trade Offer Items",
            },
        ),
        migrations.CreateModel(
            name="TradeShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="shippo", max_length=50)),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("label_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("label_created", "Label Created"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_shipments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_shipments_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ship_from_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_shipments_from",
                        to="orders.addresssnapshot",
                    ),
                ),
                (
                    "ship_to_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_shipments_to",
                        to="orders.addresssnapshot",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="trades.trade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Shipment",
                "verbose_name_plural": "Trade Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["initiator", "-created_at"],
                name="trades_trad_initiat_e7fd4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["counterparty", "-created_at"],
                name="trades_trad_counter_b0bbdb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["status"], name="trades_trad_status_623ff3_idx"),
        ),
        migrations.AddIndex(
            model_name="tradeoffer",
            index=models.Index(
                fields=["from_user", "-created_at"],
                name="trades_trad_from_us_9b33d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradeoffer",
            index=models.Index(
                fields=["to_user", "-created_at"], name="trades_trad_to_user_49e9df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeoffer",
            index=models.Index(fields=["status"], name="trades_trad_status_c072ce_idx"),
        ),
    ]
