# Generated by Django 5.0 on 2026-02-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='counter_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counteroffers', to='trades.tradeoffer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('awaiting_shipments', 'Awaiting Shipments'), ('shipped_one', 'Shipped One Side'), ('shipped_both', 'Shipped Both Sides'), ('delivered_one', 'Delivered One Side'), ('delivered_both', 'Delivered Both Sides'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='awaiting_shipments', max_length=30),
        ),
    ]
