# Generated by Django 5.0 on 2026-02-16 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('trades', '0002_tradeoffer_counter_to_alter_trade_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeshipment',
            name='carrier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tradeshipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeshipment',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeshipment',
            name='recipient_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tradeshipment',
            constraint=models.UniqueConstraint(fields=('trade', 'sender'), name='unique_trade_sender_shipment'),
        ),
    ]
