# Generated by Django 5.0 on 2026-08-05 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_minimum_offer_listingimage_image_role_and_more'),
        ('trades', '0004_tradeshipment_local_pickup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='cash_direction',
            field=models.CharField(choices=[('from_proposer', 'The proposer adds cash'), ('to_proposer', 'The proposer asks for cash')], default='from_proposer', help_text='Which way the cash runs. Meaningless while the amount is zero.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tradeoffer',
            constraint=models.CheckConstraint(check=models.Q(('cash_amount__gte', 0)), name='trade_cash_is_never_negative'),
        ),
    ]
