# Generated by Django 5.0 on 2026-08-05 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0013_tradeable_unless_you_say_otherwise'),
        ('listings', '0019_listing_minimum_offer_listingimage_image_role_and_more'),
        ('trades', '0005_cash_runs_both_ways'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='struck_trade', to='trades.tradeoffer'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='subject_item',
            field=models.ForeignKey(blank=True, help_text='The piece this negotiation is about.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_offers_about', to='collections.collectionitem'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='trade_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='listings.listing'),
        ),
    ]
