# Generated by Django 5.0 on 2026-02-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('license_year', models.IntegerField(help_text='Year the license was issued')),
                ('county', models.CharField(help_text='Pennsylvania county', max_length=50)),
                ('license_type', models.CharField(help_text='e.g., Resident, Non-resident, etc.', max_length=50)),
                ('condition_grade', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent'), ('mint', 'Mint')], max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('sold', 'Sold'), ('expired', 'Expired')], default='active', max_length=20)),
                ('featured_image', models.ImageField(help_text='Main listing image', upload_to='listings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('sort_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-auction_end'], name='listings_li_status_7979aa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['county', 'license_year'], name='listings_li_county_8246be_idx'),
        ),
    ]
