# Generated by Django 5.2.11 on 2026-02-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "__first__"),
        ("core", "__first__"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="allow_cash",
            field=models.BooleanField(
                default=False, help_text="Allow cash component in trade offers"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="buy_now_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price for buy-now listings",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="county_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="County reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="core.county",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="license_type_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="License type reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="core.licensetype",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("auction", "Auction House"),
                    ("buy_now", "General Store"),
                    ("trade", "Trading Block"),
                ],
                default="auction",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="reserve_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum price to sell (auction only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="source_collection_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Collection item this listing was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="collections.collectionitem",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="trade_notes",
            field=models.TextField(
                blank=True, help_text="What the seller is looking for in trade"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="auction_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("sold", "Sold"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["listing_type", "status"], name="listings_li_listing_1a18bd_idx"
            ),
        ),
    ]
