# Generated by Django 5.0 on 2026-02-16 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_starting_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='resident_status',
            field=models.CharField(choices=[('resident', 'Resident'), ('non_resident', 'Non-Resident'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('seller_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_questions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Question',
                'verbose_name_plural': 'Listing Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
