# Generated by Django 5.0 on 2026-03-25 04:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_listing_state(apps, schema_editor):
    Listing = apps.get_model('listings', 'Listing')
    GeographicUnit = apps.get_model('core', 'GeographicUnit')
    State = apps.get_model('core', 'State')

    pa_state = State.objects.filter(code='PA').first()
    for listing in Listing.objects.all().iterator():
        update_fields = []
        county_ref = getattr(listing, 'county_ref', None)
        if county_ref and county_ref.state_id and listing.state_id != county_ref.state_id:
            listing.state_id = county_ref.state_id
            update_fields.append('state')
        elif not listing.state_id and pa_state:
            listing.state_id = pa_state.id
            update_fields.append('state')

        if county_ref and county_ref.is_statewide != listing.is_statewide:
            listing.is_statewide = county_ref.is_statewide
            update_fields.append('is_statewide')

        if not county_ref and listing.county:
            unit = GeographicUnit.objects.filter(name__iexact=listing.county, state=listing.state).first()
            if unit:
                listing.county_ref = unit
                listing.is_statewide = unit.is_statewide
                update_fields.extend(['county_ref', 'is_statewide'])

        if update_fields:
            listing.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_referencedatasuggestion_and_more'),
        ('listings', '0005_listing_license_types_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_statewide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='shape',
            field=models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('square', 'Square'), ('button_disc', 'Button/Disc'), ('tag_with_hole', 'Tag (with hole)'), ('strip', 'Strip'), ('irregular_custom', 'Irregular/Custom'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Issuing state for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.state'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='county_ref',
            field=models.ForeignKey(blank=True, help_text='Geographic unit reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.geographicunit'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='license_type',
            field=models.CharField(blank=True, help_text='Legacy type snapshot', max_length=50),
        ),
        migrations.RunPython(backfill_listing_state, reverse_code=migrations.RunPython.noop),
    ]
