# Generated by Django 5.0 on 2026-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingquestion_moderation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='era_label',
            field=models.CharField(blank=True, choices=[('Pre-1920', 'Pre-1920'), ('1920s', '1920s'), ('1930s', '1930s'), ('1940s', '1940s'), ('1950s', '1950s'), ('1960s', '1960s'), ('1970s', '1970s'), ('1980s', '1980s'), ('1990s', '1990s'), ('2000', '2000')], help_text='Decade era — set automatically when license_year is known; required when year is unknown', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='serial_number',
            field=models.CharField(blank=True, help_text='License serial or stub number, if visible', max_length=100),
        ),
    ]
