# Generated by Django 5.0 on 2026-04-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_era_label_listing_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='license_year',
            field=models.IntegerField(blank=True, help_text='Year the license was issued', null=True),
        ),
    ]
