# Generated by Django 5.0 on 2026-04-01 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_collectionitem_era_label_and_more'),
        ('core', '0005_referencedatasuggestion_and_more'),
        ('listings', '0010_listing_year_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['license_year'], name='listing_license_year_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['era_label'], name='listing_era_label_idx'),
        ),
    ]
