# Generated by Django 5.0 on 2026-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_backfill_item_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('auction', 'The Auction House'), ('buy_now', 'The General Store'), ('trade', 'The Trading Block')], default='auction', max_length=20),
        ),
    ]
