# Generated by Django 5.0 on 2026-07-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_messaging_disabled'),
        ('listings', '0014_the_marketplace_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='package_height_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='package_length_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='package_weight_oz',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Package weight in ounces', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='package_width_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='ship_from_address',
            field=models.ForeignKey(blank=True, help_text='Ship-from address (defaults to your account default address)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_shipping_from', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_payer',
            field=models.CharField(choices=[('buyer', 'Buyer pays shipping'), ('seller', 'Seller pays (free shipping)')], default='buyer', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_service',
            field=models.CharField(choices=[('cheapest', 'Best available (cheapest rate)'), ('usps_ground_advantage', 'USPS Ground Advantage'), ('usps_priority', 'USPS Priority Mail'), ('ups_ground', 'UPS Ground'), ('fedex_ground', 'FedEx Ground'), ('fedex_2_day', 'FedEx 2-Day')], default='cheapest', help_text='Carrier/service passed through to Shippo when quoting', max_length=30),
        ),
    ]
