# Generated by Django 5.0 on 2026-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_shipping_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='license_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum amount each new bid must exceed the current bid by', max_digits=8),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition_grade',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent'), ('near_mint', 'Near Mint'), ('mint', 'Mint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, default='', help_text='Denormalized display snapshot — county_ref/is_statewide are authoritative', max_length=50),
        ),
    ]
