# Generated by Django 5.0 on 2026-07-31 21:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_form_overhaul_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum amount each new bid must exceed the current bid by', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for buy-now listings', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price to sell (auction only)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
