# Generated by Django 5.0 on 2026-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_bid_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allow_offers',
            field=models.BooleanField(default=False, help_text='Let buyers negotiate with a binding offer below your asking price'),
        ),
    ]
