# Generated by Django 5.0 on 2026-08-05 05:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_allow_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='minimum_offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offers below this are declined for you, and the buyer is told why. Leave it empty and every offer reaches you.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_role',
            field=models.CharField(choices=[('front', 'Featured · front'), ('back', 'Back'), ('detail', 'Detail')], default='detail', help_text='What this photograph is of. Front and back are the two a buyer looks for; everything else is a detail.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('image_role__in', ('front', 'back'))), fields=('listing', 'image_role'), name='one_photograph_per_named_slot'),
        ),
    ]
