# Generated by Django 5.0 on 2026-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_minimum_offer_listingimage_image_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('closed', 'Closed'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
