# Generated by Django 5.0 on 2026-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_condition_description_listing_is_restored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition_grade',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very good'), ('excellent', 'Excellent'), ('near_mint', 'Near mint'), ('mint', 'Mint')], max_length=20),
        ),
    ]
