# Generated by Django 5.0 on 2026-08-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_listing_condition_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_extensions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
