# Generated by Django 5.0 on 2026-08-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_auction_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this lot last went live — the "Listed" date shown to buyers', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
