# Generated by Django 5.0 on 2026-02-16 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
        ('listings', '0002_listing_allow_cash_listing_buy_now_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['listing', '-amount', 'placed_at'], name='bids_bid_listing_5c0678_idx'),
        ),
    ]
