# Generated by Django 5.0 on 2026-08-26 23:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_amount'),
        ('listings', '0022_alter_listing_condition_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_proxy',
            field=models.BooleanField(default=False, help_text='Placed automatically on the bidder’s behalf by their standing maximum.'),
        ),
        migrations.CreateModel(
            name='ProxyMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_maxes', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_maxes', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Proxy maximum',
                'verbose_name_plural': 'Proxy maximums',
            },
        ),
        migrations.AddConstraint(
            model_name='proxymax',
            constraint=models.UniqueConstraint(fields=('listing', 'bidder'), name='one_standing_max_per_bidder'),
        ),
    ]
