# Generated by Django 5.2.11 on 2026-02-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enforcement", "0002_initial"),
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strike",
            name="related_trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strikes",
                to="trades.trade",
            ),
        ),
        migrations.AddField(
            model_name="strike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="strike",
            index=models.Index(
                fields=["user", "-created_at"], name="enforcement_user_id_73354f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strike",
            index=models.Index(
                fields=["is_excused"], name="enforcement_is_excu_70a208_idx"
            ),
        ),
    ]
