# Generated by Django 5.0 on 2026-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='excuse_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='excuse_note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='strike',
            name='excuse_reason',
            field=models.CharField(blank=True, choices=[('local_pickup', 'Local Pickup'), ('agreed_delay', 'Agreed Delay'), ('combined_shipment', 'Combined Shipment'), ('alternative_delivery', 'Alternative Delivery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strike',
            name='reason',
            field=models.CharField(choices=[('non_shipment', 'Non Shipment'), ('non_payment', 'Non Payment'), ('cancellation_abuse', 'Cancellation Abuse'), ('other', 'Other')], max_length=50),
        ),
    ]
