# Generated by Django 5.0 on 2026-08-05 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0004_strike_excuse_expires_at_alter_strike_excuse_note_and_more'),
        ('orders', '0004_order_order_buyer_is_not_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHandshake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers', models.CharField(choices=[('shipping', 'The shipping deadline'), ('receipt', 'Confirming it arrived')], max_length=20)),
                ('reason', models.CharField(choices=[('local_pickup', 'Local Pickup'), ('agreed_delay', 'Agreed Delay'), ('combined_shipment', 'Combined Shipment'), ('alternative_delivery', 'Alternative Delivery'), ('other', 'Other')], max_length=50)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handshakes_confirmed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handshakes', to='orders.order')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handshakes_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Handshake',
                'verbose_name_plural': 'Order Handshakes',
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['order', 'covers', '-proposed_at'], name='enforcement_order_i_7d2435_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderhandshake',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False)), _connector='OR'), name='handshake_confirmation_is_whole'),
        ),
        migrations.AddConstraint(
            model_name='orderhandshake',
            constraint=models.CheckConstraint(check=models.Q(('confirmed_by', models.F('proposed_by')), _negated=True), name='handshake_needs_two_people'),
        ),
    ]
