# Generated by Django 5.0 on 2026-04-01 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_delivery_method'),
        ('trades', '0004_tradeshipment_local_pickup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('body', models.TextField(blank=True, max_length=255)),
                ('moderation_state', models.CharField(choices=[('ok', 'OK'), ('flagged', 'Flagged'), ('hidden', 'Hidden')], default='ok', help_text='ok = visible; flagged = visible but under review; hidden = removed from public view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='trades.trade')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed_user', '-created_at'], name='reviews_rev_reviewe_4202d8_idx'), models.Index(fields=['moderation_state'], name='reviews_rev_moderat_d74ffd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('reviewer', 'order'), name='unique_review_per_order_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('trade__isnull', False)), fields=('reviewer', 'trade'), name='unique_review_per_trade_reviewer'),
        ),
    ]
