# Generated by Django 5.0 on 2026-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Good'), ('neutral', 'Middling'), ('negative', 'Poor')], max_length=10),
        ),
    ]
