# Generated by Django 5.0 on 2026-07-23 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0008_backfill_item_kind'),
        ('listings', '0013_backfill_item_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prefill/%Y/%m/')),
                ('source_form', models.CharField(choices=[('listing', 'Listing'), ('collection', 'Collection')], default='collection', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolving', 'Resolving'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_extraction', models.JSONField(blank=True, help_text='Raw VLM output', null=True)),
                ('resolved_payload', models.JSONField(blank=True, help_text='Tier-tagged, form-ready payload', null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('prompt_version', models.CharField(blank=True, help_text='Hash of prompt + extraction schema (prefill/config/) at run time', max_length=20)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefill_jobs', to='collections.collectionitem')),
                ('resulting_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefill_jobs', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefill_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prefill Job',
                'verbose_name_plural': 'Prefill Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrefillCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('suggested_value', models.JSONField(blank=True, null=True)),
                ('final_value', models.JSONField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=10)),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='prefill.prefilljob')),
            ],
            options={
                'verbose_name': 'Prefill Correction',
                'verbose_name_plural': 'Prefill Corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prefilljob',
            index=models.Index(fields=['user', '-created_at'], name='prefill_pre_user_id_c4771a_idx'),
        ),
        migrations.AddIndex(
            model_name='prefilljob',
            index=models.Index(fields=['status', '-created_at'], name='prefill_pre_status_10a750_idx'),
        ),
        migrations.AddIndex(
            model_name='prefillcorrection',
            index=models.Index(fields=['field_name', 'tier'], name='prefill_pre_field_n_505b2b_idx'),
        ),
    ]
