# Generated by Django 5.2.11 on 2026-02-16 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_sent_354551_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sent",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_url",
            field=models.CharField(
                blank=True, help_text="URL to navigate to on click", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("outbid", "Outbid"),
                    ("auction_won", "Auction Won"),
                    ("auction_sold", "Auction Sold"),
                    ("auction_expired", "Auction Expired"),
                    ("payment_received", "Payment Received"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("order_created", "Order Created"),
                    ("order_paid", "Order Paid"),
                    ("order_shipped", "Order Shipped"),
                    ("order_delivered", "Order Delivered"),
                    ("order_completed", "Order Completed"),
                    ("trade_offer_received", "Trade Offer Received"),
                    ("trade_offer_accepted", "Trade Offer Accepted"),
                    ("trade_offer_declined", "Trade Offer Declined"),
                    ("trade_offer_countered", "Trade Offer Countered"),
                    ("trade_ship_reminder", "Trade Ship Reminder"),
                    ("trade_shipped", "Trade Shipped"),
                    ("trade_delivered", "Trade Delivered"),
                    ("trade_completed", "Trade Completed"),
                    ("strike_issued", "Strike Issued"),
                    ("strike_excused", "Strike Excused"),
                    ("account_restricted", "Account Restricted"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sent_email", "created_at"],
                name="notificatio_sent_em_65dfa6_idx",
            ),
        ),
    ]
