# Generated by Django 5.0 on 2026-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('outbid', 'Outbid'), ('auction_won', 'Auction Won'), ('auction_sold', 'Auction Sold'), ('auction_expired', 'Auction Expired'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('order_created', 'Order Created'), ('order_paid', 'Order Paid'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_completed', 'Order Completed'), ('trade_offer_received', 'Trade Offer Received'), ('trade_offer_accepted', 'Trade Offer Accepted'), ('trade_offer_declined', 'Trade Offer Declined'), ('trade_offer_countered', 'Trade Offer Countered'), ('trade_offer_expired', 'Trade Offer Expired'), ('listing_question_received', 'Listing Question Received'), ('listing_question_answered', 'Listing Question Answered'), ('order_ship_reminder', 'Order Ship Reminder'), ('receipt_confirmation_pending', 'Receipt Confirmation Pending'), ('trade_ship_reminder', 'Trade Ship Reminder'), ('trade_shipped', 'Trade Shipped'), ('trade_delivered', 'Trade Delivered'), ('trade_completed', 'Trade Completed'), ('strike_issued', 'Strike Issued'), ('strike_excused', 'Strike Excused'), ('account_restricted', 'Account Restricted')], max_length=50),
        ),
    ]
