# Generated by Django 5.0 on 2026-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('outbid', 'Outbid'), ('auction_won', 'Auction Won'), ('auction_sold', 'Auction Sold'), ('auction_expired', 'Auction Expired'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('payment_after_cancel', 'Payment After Cancellation'), ('payment_needs_refund', 'Payment Needs Refund'), ('order_created', 'Order Created'), ('order_paid', 'Order Paid'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_completed', 'Order Completed'), ('trade_offer_received', 'Trade Offer Received'), ('trade_offer_accepted', 'Trade Offer Accepted'), ('trade_offer_declined', 'Trade Offer Declined'), ('trade_offer_countered', 'Trade Offer Countered'), ('trade_offer_expired', 'Trade Offer Expired'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('offer_countered', 'Offer Countered'), ('offer_expired', 'Offer Expired'), ('listing_question_received', 'Listing Question Received'), ('listing_question_answered', 'Listing Question Answered'), ('order_ship_reminder', 'Order Ship Reminder'), ('receipt_confirmation_pending', 'Receipt Confirmation Pending'), ('trade_ship_reminder', 'Trade Ship Reminder'), ('trade_shipped', 'Trade Shipped'), ('trade_delivered', 'Trade Delivered'), ('trade_completed', 'Trade Completed'), ('strike_issued', 'Strike Issued'), ('strike_excused', 'Strike Excused'), ('handshake_requested', 'Handshake Requested'), ('handshake_confirmed', 'Handshake Confirmed'), ('account_restricted', 'Account Restricted'), ('new_message', 'New Message'), ('moderation_urgent', 'Moderation Urgent')], max_length=50),
        ),
    ]
